### ISSUE TITLE
Embed does not work on .be domains

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#150]
**Brief description**

Embeds don't appear to work on `.be` domains

**How to reproduce**

https://cytu.be/twitch-test.html

this example clip embed appears to be correctly configured. But throws a

```
Twitch embed error message:[FailedAttributeCheck] mandatory requirements were not metDocs: https://dev.twitch.tv/docs/embed/video-and-clips/
```

**Expected behavior**

The embed works

**Screenshots**

![image](https://user-images.githubusercontent.com/20999/85539552-e0c41b80-b60d-11ea-9cae-61e6ad14ba20.png)

**Additional context or questions**

Original report

https://discuss.dev.twitch.tv/t/embed-api-parent-parameter-not-working-for-specific-domain/26671/

**Comment by jbulava** [comment]
I cannot test .be domains at the moment, but it looks like there might actually be issues with the embed code.  Can we try correcting those first before assume the domain?

The embed URL on https://cytu.be/twitch-test.html has `&amp;` instead of `&` before the parent, so this value is not being found. That should fix the misconfiguration.  The clip trying to be embedded also does not exist. Let us know and provide an example if the URL fix and using an existing Clip does not work.

**Comment by calzoneman** [comment]
>The embed URL on https://cytu.be/twitch-test.html has &amp; instead of & before the parent, so this value is not being found.

The `&amp;` in the page source is an XML escape -- technically putting `&parent` in a string would be incorrect HTML.  However, I have updated it just to be sure, and the result is the same.

>The clip trying to be embedded also does not exist.

Updated to one that does exist.  Same error.

**Comment by calzoneman** [comment]
Btw the exact same page source (with the domain changed) works: https://beta.synchtube.me/twitch-test.html

So it does seem to be related to the specific domain name being used.

**Comment by jbulava** [comment]
Thanks for making the updates.  Is there a specific error message that you see?  The embed appears to be working ok from here.

![Screen Shot 2020-06-24 at 4 00 21 PM](https://user-images.githubusercontent.com/533789/85621868-f3514b80-b633-11ea-84cf-a718bc601cd5.png)

**Comment by jbulava** [comment]
Got it, can confirm that the only difference appears to be the .be domain. Inquiring with the embed team.

**Comment by calzoneman** [comment]
Thanks!

**Comment by calzoneman** [comment]
Any update on this?

**Comment by calzoneman** [comment]
It's now been about 2 weeks and my website embeds are still broken despite folks on this thread indicating my embed parameters are correct, is there a path forward to getting this resolved?

**Comment by calzoneman** [comment]
Hi,

It has now been about 3 weeks.  I know we are all busy, but is there any estimate on when this can be fixed?  I really don't want to have to migrate everything to new domain name just to make the Twitch API work...

**Comment by Edudls** [comment]
Hi @jbulava 
Is there any update on this? It's been almost 2 months and this is still an open issue.

**Comment by jbulava** [comment]
Apologies for the long delay to respond to this issue. I wanted to make sure that I understood all of the details talking with other teams and that we had the right information to share. This is not applicable for all .be domains as was mentioned when opening the ticket, but does include cytu.be.

Twitch retains the right to restrict the domains on which its embeddable experiences may be used. Twitch embeds may not be used on websites that have a primary purpose to share or host content that would violate Twitch’s [Terms of Service](https://www.twitch.tv/p/legal/terms-of-service/) or [Community Guidelines](https://www.twitch.tv/p/legal/community-guidelines/). The website above was determined to have such a primary purpose, and we have therefore restricted our embeddable experiences from appearing there.

**Comment by calzoneman** [comment]
Hi Jon,

Really appreciate you getting back to me.  I'd like to follow up on a couple questions if you don't mind:

1. Could you please direct me to the right location to privately discuss with Twitch the specific problem which led to this block and how to remediate it?  I assume Twitch would prefer not to discuss that on a public issue tracker, but I would like to follow up on it -- the site in question hosts user-generated content and I never received any specific complaints from Twitch so I'd love to hear about those and resolve them so that those users who are complying with Twitch's terms of service can continue to use it.
2. Is it possible to change the error message that is displayed in this scenario?  If I knew from the beginning that my embed was blocked due to a ToS issue, it would have saved a lot of back and forth churn on the developer forum and here.

**Comment by jbulava** [comment]
Apologies for an extremely long delay to your followup questions.  At the time, we did not have a process in place for appeals or remediation.  You can now do this by [filing a support ticket](https://help.twitch.tv/s/contactsupport).  Select the "General" category and "Community Guidelines Questions/Appeals" sub-category when submitting.  Your request will be routed to someone who can speak to you directly regarding embeds policy.

The confusion around the error message is understandable and has also been brought up for discussion.
