### ISSUE TITLE
OAuth2 doesnt work

### ISSUE THREAD

**Issue by Krypt0nC0R3** [twitchdev/issues#166]
**Brief description**
I get OAuth2 token by my application. I cat validate this OAuth2 token by https://id.twitch.tv/oauth2/validate, but i cant login into chat websocket server.
**How to reproduce**
Get OAuth2 with:

- Client ID: `u61ewzlqe0aaooi84qutm2tue68sw9`
- Scopes: `channel:moderate, chat:edit, user_read`
- Response type: `Token`
- Force verify: `true`
- Redirect URI: `http://localhost:6580/index.html`

With this token i try login and got `> :tmi.twitch.tv NOTICE * :Login unsuccessful`
**Expected behavior**
```
> :tmi.twitch.tv 001 <user> :Welcome, GLHF!
> :tmi.twitch.tv 002 <user> :Your host is tmi.twitch.tv
> :tmi.twitch.tv 003 <user> :This server is rather new
> :tmi.twitch.tv 004 <user> :-
> :tmi.twitch.tv 375 <user> :-
> :tmi.twitch.tv 372 <user> :You are in a maze of twisty passages.
> :tmi.twitch.tv 376 <user> :>
```
**Screenshots**
OAuth2 validate:
![Bug1](https://user-images.githubusercontent.com/46594859/87507870-5d3f9c80-c698-11ea-8dd6-4418b078692d.PNG)

Login into chat server:
![Bug2](https://user-images.githubusercontent.com/46594859/87507955-84966980-c698-11ea-8988-35174b1b1364.PNG)
**Additional context or questions**
 Maybe i do something wrong?

**Comment by n0xena** [comment]
First of all: Please post CODE instead of screenshots ...
Second: NEVER EVER AT ALL TIMES post SECRET credentials in public - this can lead to major security vulnerabilities
As for your issue: You most likely missing the chat:read scope - only chat:edit might not be enough - but doc isn't clear about it as it only says chat:read is for reading messages and chat:edit for send messages - it's quite possible connection isn't able at all without chat:read scope as you would only be able to send messages without reading any reply ... even for a bot not really usefull.
https://dev.twitch.tv/docs/irc/guide

**Comment by Krypt0nC0R3** [comment]
Thx, I add chat:read to my scope and this works!

**Comment by n0xena** [comment]
> Thx, I add chat:read to my scope and this works!

Thank you for reporting back that adding the chat:read scope in fact did solve this issue. Maybe this should be re-opened so the doc could be re-phrased to something more precise.
