### ISSUE TITLE
helix/subscriptions is not returning all subscribers

### ISSUE THREAD

**Issue by brandinarsenault** [twitchdev/issues#184]
**Brief description**
While paginating through subscriptions (showing on the Dashboard as 789) - I am only able to get to 702. This wasn't an issue until the past few days, it worked without a problem before. I have tested my code to ensure that it isn't ending pagination early, the last page, which has 2 results, has no cursor. 

**How to reproduce**
Query helix/subscriptions for 100 and paginate until you receive 0 results or no cursor, compare the count

**Expected behavior**
You should be able to retrieve 100% of the subscribers from this endpoint through pagination.

(Feature request) We would have access to a count field when not specifying the optional user_id.

**Screenshots**
![image](https://user-images.githubusercontent.com/15201621/89255873-328e9700-d5f9-11ea-83a8-789ade783062.png)

**Additional context or questions**
N/A - feel free to ask for more information, I'd be happy to help.

**Comment by night** [comment]
It looks like internally their pagination cursor seems to work on a datetime field. Out of curiosity, do the missing subscriptions share the timestamp of another subscription?

**Comment by csunday95** [comment]
@night I also posted a very similar issue #187. In my case, all the missing subs were correlated with large gifted sub chunks (e.g. someone gifting a set of 50).

**Comment by night** [comment]
@csunday95 i mean that would make sense if my theory is correct.. those subs might share the same timestamp internally, which breaks pagination. you can see the timestamps on v5, but it looks like they removed them on helix.

**Comment by brandinarsenault** [comment]
This would match up with your theory and could be encouraged by the data that @csunday95 was able to extract. This issue was supposed to be reviewed by the Staff recently but haven't seen an update, hopefully this gets resolved soon. Does it seem like however, the v5 endpoint might be more reliable right now for this data?

**Comment by lleadbet** [comment]
Ticketed internally as SUBS-6778. Appreciate the report.

**Comment by pietrodicaprio** [comment]
> 
> 
> Ticketed internally as SUBS-6778. Appreciate the report.

Dear @lleadbet, any news since the creation of the internal ticket?

**Comment by lleadbet** [comment]
We're still digging into it, but hoping to have an update soon.

**Comment by pietrodicaprio** [comment]
> 
> 
> We're still digging into it, but hoping to have an update soon.

Mh, I would go for commenting the code part that uses Helix in order to switch to V5 but I need to ask all my broadcasters to login again in order to add the V5 scope to their token...
There is a 3500 subscribers broadcaster that is having issues every day due to this bug. The most strange thing is that are not always the same users that are missing from the API call. I see that is almost random, an user present right now could be missing tomorrow and for an unknown time.

**Comment by lleadbet** [comment]
Can someone send me an example user that's seeing this issue? I can be reached on the TwitchDev Discord as ConcreteEntree.

**Comment by brandinarsenault** [comment]
@lleadbet I'll send you something shortly.

**Comment by lleadbet** [comment]
Hey everyone- great news! We have a fix rolling out shortly (within the next few minutes) to address these issues. 

One important note- the count on the dash and total from the API will always be exactly 1 off, since the dash filters out the broadcaster's own subscription to their channel, whereas the API does not. Otherwise, they should match. 

Thanks again for all the information and patience here!
