### ISSUE TITLE
Helix Streams - Surprise Pagination!

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#2]
**Brief description**

The helix streams API is returning a pagination cursor in cases where it shouldn't.

Some example requests

https://discuss.dev.twitch.tv/t/get-streams-repeatedly-returning-cursor-ia/23348

This one is a recurrence of a issue that has happened before.

**How to reproduce**

Call the streams helix endpoint specifying a single user_id or login

Call when live:

https://api.twitch.tv/helix/streams?user_login=cohhcarnage

https://api.twitch.tv/helix/streams?user_id=30661033

Returns a pagination

```
"pagination": {
"cursor": "IA"
}
```

**Expected behavior**

No pagination key to be present in the JSON output when pagination shouldn't occur

**Comment by mauerbac** [comment]
+1 
`Sometimes it returns an invalid cursor that is actually two cursors, space-concatenated, and 
 base64-encoded a second time.`

**Comment by mkwatson** [comment]
+1
what @mauerbac said!

**Comment by MrSpock78** [comment]
Is this the same issue?
https://discuss.dev.twitch.tv/t/cursor-is-not-null-anymore-when-there-is-no-next-page/23372

**Comment by jbulava** [comment]
> +1
> `Sometimes it returns an invalid cursor that is actually two cursors, space-concatenated, and base64-encoded a second time.`

This is expected and is valid. The change in cursor is due to an internal infrastructure change, however passing in the full value of `cursor` should behave as usual.

We'll investigate if the NA cursor is expected with the infrastructure change.

**Comment by thedist** [comment]
Just adding some suggestions that have come up since the launch of this endpoint on ways that pagination could be improved.

The goal of any solution would be for any dev paging through any Helix endpoint to have a clear and reliable indication of "there are no more results, you can stop pagination".

Currently, the final page of the Streams endpoint still contains a cursor (for use in `before`) so simply relying on the lack of a cursor can't work.

One solution may be for Twitch to validate the cursor on their end, so for example if that final cursor is used as the `after` value, rather than returning to page 1 (like what would happen with any request lacking or having a bad `after` value) there could be a check and if that cursor isn't appropriate for paging forwards then there could be a response with just an empty data array, and a cursor that allows paging backwards still with `before` but the same `after` object in the cursor so any repeated use will just return to the same final/empty page rather than the start.

Another suggestions that has come up would be for the inclusion of an additional pagination value in addition to the already existing cursor that the endpoint returns that can be a simple flag to indicate if there are more results (this could also be used to indicate if you're on Page 1, so unable to use the `before` param).

A final suggestion would be is if it's possible to encode metadata related to the pagination state in the cursor, so Base64 decoding it could give a dev details such as if they're on the final page, their current page, etc... I don't think this would be the most user friendly option though, as ideally devs shouldn't need to touch with the Decoding of a cursor.

All of these ideas should be non-breaking, as they don't change has cursors function, from the dev side of things and I think the first option, of the final cursor returning a page with an empty data array could be best as this would stop any endless loops in existing implementations, where as additional flags wouldn't help until the dev integrates that into their apps.

**Comment by mauerbac** [comment]
HLX-1316

**Comment by lleadbet** [comment]
Closing the loop, we've addressed the IA issue on this endpoint. If you're continuing to see this, please feel free to reopen this issue. 

If you continue to see other issues, please feel free to reopen an issue with more information.
