### ISSUE TITLE
The hidden parameter `force_login`

### ISSUE THREAD

**Issue by TroyDota** [twitchdev/issues#228]
**Brief description**
Although undocumented there is a parameter `force_login` which forces the user to login again. In my case this actually logs out of my twitch account without me wanting to and can be very annoying. 
**How to reproduce**
Send the `force_login=true` parameter to the auth endpoint
**Expected behavior**
Requires the user to login but does not log you out of your twitch account.
**Screenshots**

**Additional context or questions**

**Comment by timcole** [comment]
Hey, is there a reason you'd like to force your users to login to their Twitch account again? Personally seems like an annoying UX decision.

I use personally use `force_verify` which is documented [here](https://dev.twitch.tv/docs/authentication/getting-tokens-oauth#oauth-implicit-code-flow) and forces the use to click allow again but doesn't require them to completely login to Twitch.

It's important to note the since this is an undocumented parameter you're after it's highly recommended not to use it in any production environments. Undocumented items have no guarantees and can/(will) change or go away at any time without warning.

**Comment by TroyDota** [comment]
Oh I don't want to use it. I just don't like that it logs out of my twitch account without prior warning. I use a password manager but I am almost 100% sure that majority of users likely 1. Don't use a password manager or 2. Have forgotten their password. Which makes logging out an unnecessary reset. Since this call has little to no user input. I just thought it strange it would even exist in the first place.

**Comment by lleadbet** [comment]
Hello - Apologies for the delay on this. 

This is technically not a bug on our side, as it's an intentional flag. Appreciate you flagging this, however!
