### ISSUE TITLE
dev.twitch.tv/request-access form will not submit

### ISSUE THREAD

**Issue by AlexBezuska** [twitchdev/issues#242]
**Brief description**
dev.twitch.tv/request-access form will not submit

**How to reproduce**
Fill out the form at dev.twitch.tv/request-access and attempt to use the capcha and hit the submit button.

**Expected behavior**
Form would allow a user to use the capcha and submit, or give a helpful error of some kind.

**Screenshots**
Video -- > https://twitter.com/TwoScoopGames/status/1316521401453608962

**Additional context or questions**

**Comment by jbulava** [comment]
Thanks for the Issue and Tweet. Reaching out to the developer site team to investigate.

**Comment by jbulava** [comment]
Hi Alex, it turns out we're missing an error message in the case where an organization already exists.  We'll resolve that separately from your specific inquiry.

Our records show that you are the owner of the organization for Two Scoop Games; it was created some time ago.  I would like to follow up directly to confirm which Twitch account owns the organization.  Let me know if I should send a Twitter DM to the TwoScoopGames account, or you can feel free to send me a Twitter DM at /jbulava.
