### ISSUE TITLE
Immortals Fenyx Rising Twitch Extension won't install.

### ISSUE THREAD

**Issue by valheru7** [twitchdev/issues#294]
**Brief description**

Immortals Fenyx Rising Twitch Extension won't install.

I can't even FIND the extension if I search for it....it just pops up telling me I should install it when I set my twitch game to Immortals Fenyx Rising...thats the only way I even found out about it.

No other errors etc. 

I try to go to Extension details and it shows a nice summary and a screenshot but no add button and nothing else. If I go back to discovery, a helpful window pops up saying I should continue adding it but if I tap add to channel, it sends me to a screen that is perpetually loading with an activate button that does nothing.

**How to reproduce**

1. Go to Stream manager
2. Set Stream category to Immortals Fenyx Rising
3. See extra panel advertising the Fenyx Rising Monster Hunt Extension
4. Try to install it

**Expected behavior**

The extension installs and works.

**Screenshots**

<img width="829" alt="Screen Shot 2021-01-28 at 6 20 31 PM" src="https://user-images.githubusercontent.com/5475053/106223355-17f73e00-6196-11eb-9af3-42539c61acbd.png">
<img width="670" alt="Screen Shot 2021-01-28 at 6 21 37 PM" src="https://user-images.githubusercontent.com/5475053/106223366-1ded1f00-6196-11eb-900b-24577723e4b8.png">
<img width="1447" alt="Screen Shot 2021-01-28 at 6 21 45 PM" src="https://user-images.githubusercontent.com/5475053/106223370-1e85b580-6196-11eb-8810-663448adaf8b.png">
<img width="1569" alt="Screen Shot 2021-01-28 at 6 21 28 PM" src="https://user-images.githubusercontent.com/5475053/106223360-1a599800-6196-11eb-9699-63ede8ee3783.png">

**Additional context or questions**

**Comment by jbulava** [comment]
Are you able to install the Extension from the latest version linked below? It might be different from the popup mentioned above. https://dashboard.twitch.tv/extensions/ipx5qzf014tftw1lf969z4j19zg6w1-0.0.3

I'm also checking if there are any issues with Extension installs in general. If the above link doesn't work, I would also suggest contacting the Ubisoft support email listed in the screenshot as they are the administrators of the Extension.

It may also be possible that the Extension is no longer supposed to be installable since [their announcement](https://support.ubisoft.com/en-US/Article/000093904/Information-about-the-Monster-Hunt-Twitch-extension-for-Immortals-Fenyx-Rising) suggests it would only be available until December 14.

**Comment by valheru7** [comment]
Hi jon 

Thanks for the quick follow-up! You are correct. I should learn to read lol

That being said, it seems like they should remove the extension / reminder when adding the game category as it does seem to advertise that it's still available. 

I did open a case with ubisoft too 

Thanks! 

-----

**Comment by lleadbet** [comment]
@valheru7 - Just as a followup, the suggestion to install has been removed. As a result, I'm going to close this- appreciate you flagging this!
