### ISSUE TITLE
Can't get past Developer Agreement

### ISSUE THREAD

**Issue by carlhihat** [twitchdev/issues#379]
**Brief description**
I had already completed the Dev onboarding at settings/revenue/payout-onboarding, but then had to go back and change some info in part 1. Now I can't get past step 2. "INTERNAL_ERROR" is returned when pressing the "next"-button. 

`"acceptProgramAgreement":{"workflow":null,"error":"INTERNAL_ERROR","__typename":"AcceptProgramAgreementPayload"}`

I suspect this issue might occur when the agreement has already been signed previously, because I found another user in the discord who had the same issue at the same "state".

**Comment by plasticlobster** [comment]
I have this issue as well. Have been trying to get Twitch support to help me since Saturday ( https://twitter.com/TwitchSupport/status/1386824768821899287 )

I'm stuck too. The only difference is I've never completed the settings/revenue/payout-onboarding registration in the past. I've just accepted the general developer terms.

**Comment by carlhihat** [comment]
Appears to be fixed as it is currently working for both me and plasticlobster!

**Comment by lleadbet** [comment]
Just to confirm, we've deployed a fix to resolve this. Thanks for the confirmation!
