### ISSUE TITLE
GET - Channels - 30944869 returns the wrong channel

### ISSUE THREAD

**Issue by twitch-chandog** [twitchdev/issues#416]
**Brief description**
Passing 30944869 (E3's channel) to /channels returns back 12826 (Twitch's channel)

**How to reproduce**
https://api.twitch.tv/kraken/channels/30944869

**Expected behavior**
Expected to return E3's channel

**Screenshots**
![image](https://user-images.githubusercontent.com/84536162/121968604-9f59de00-cd40-11eb-9005-b81cc2d125cc.png)

**Comment by zneix** [comment]
Small note that this issue does not occur upon making a Helix call.

**Comment by MattBroach** [comment]
Looks like another instance of this bug: https://github.com/twitchdev/issues/issues/401

**Comment by travistyoj** [comment]
Thanks for the report. Unfortunately, these issues can sometimes surface due to the underlying nature of the legacy v5 API. Can you elaborate on why if this version is preferred for your use instead of the Helix version?

**Comment by MattBroach** [comment]
Sure, happy to.  In our case, it's simply that we're collecting `followers` and `total_views` on a large number of channels.  In the V5 API these could be collected from a single endpoint, but in on helix we need to collect these from multiple endpoints.  Of course, when helix was originally released there wasn't even a way to get total followers -- this has since been fixed (thank you), but there's still both development effort and increased load/activity on our servers to collect the same data from multiple endpoints which we have preferred not to expend, as long as kraken was extent and stable.

**Comment by twitch-chandog** [comment]
> Thanks for the report. Unfortunately, these issues can sometimes surface due to the underlying nature of the legacy v5 API. Can you elaborate on why if this version is preferred for your use instead of the Helix version?

Just to echo what Matt said.. v5 gives you a lot more data in one call.

**Comment by twitch-chandog** [comment]
@travistyoj Any update on this? Still persists.

**Comment by MattBroach** [comment]
I'm guessing that since they announced a final [shutdown for Kraken](https://discuss.dev.twitch.tv/t/legacy-twitch-api-v5-shutdown-details-and-timeline/32649), they aren't going to release any more fixes for v5.  Time to migrate our apps, I guess...

**Comment by Xemdo** [comment]
Kraken has shut down as of January 2023, and the bug appears to have not resurfaced in Helix.
If it does, please let us know by reopening this issue.
