### ISSUE TITLE
Missing docs in IRC: Tags PRIVMSG 

### ISSUE THREAD

**Issue by Toerktumlare** [twitchdev/issues#552]
**Brief description**
When developing against the provided docs on the IRC: Tags PRIVMSG https://dev.twitch.tv/docs/irc/tags#privmsg-twitch-tags page there are several parameters that are undocumented. Examples show undocumented parameters.

the provided example of a message shows several undocumented parameters
```
> @badge-info=;
badges=global_mod/1,turbo/1;
color=#0D4200;
display-name=ronni;
emotes=25:0-4,12-16/1902:6-10;
id=b34ccfc7-4977-403a-8a94-33c6bac34fb8;
mod=0;
room-id=1337;
subscriber=0; < ----------------- undocumented
tmi-sent-ts=1507246572675;
turbo=1;  < ---------------- undocumented
user-id=1337;
user-type=global_mod   <------------ undocumented
:ronni!ronni@ronni.tmi.twitch.tv PRIVMSG #ronni :Kappa Keepo Kappa
```

other inconsistencies are that the provided documentation does not say if a value is optional or not for instance:

```
message | The message body sent by the user.
```

is declared in the documentation as non optional, but is nowhere to be seen in the examples provided, so here my question is, does this value even exist?

**Expected documentation**

My suggestion is that the documentation should be reviewd and most prefferable be updated with the following table:

| Parameter | optional | example value | can be empty | description |
|---|---|---|---|---|
|badges| no | mod/1| yes | Comma-separated list of chat badges and the version of each badge... |

In general the documentation seems to be needing a look over.

**Comment by BarryCarlyon** [comment]
Both `user_type` and `subscriber` are actaully deprecated

Hence the yare removed from the docs and should not be rely upon

**Comment by Tandolf** [comment]
im sorry for typing `mod/1` i know this is incorrect. what i actually meant was `global_mod` which is a badge.

What i wanted to point out was that the example message still contains the deprecated values, and so that the actual data when i connect to twitch. But there is no mention of the parameters in the docs.

That got me confused, since then you dont really know, what these parameters are for.

it would have been better if all parameters where disclosed in the docs, while those that are deprecated would be marked as deprecated.

But thank you for all the info.

**Comment by Xemdo** [comment]
All expected IRC tags are now documented: https://dev.twitch.tv/docs/chat/irc/#irc-tag-reference

PRIVMSG specifically: https://dev.twitch.tv/docs/chat/irc/#privmsg-tags
