### ISSUE TITLE
Twitch Extension does not load

### ISSUE THREAD

**Issue by ronaksv** [twitchdev/issues#560]
**My twitch extension (twitch-id: subxliveshows) is in production since past couple of months and it was working fine since yesterday but now it is not loading up**

I feel this is related to your email a few days back regarding restricting the media and resources unless the URLs are whitelisted on the dev console.

I have updated the console as per your request as seen below in screenshot.
![image](https://user-images.githubusercontent.com/6523165/151490905-27fb72be-ee9c-4abe-8e46-c2ff7867a852.png)

Still the extension is not loading up.
Also an unusual thing happened today. For 10-15 minutes the extension did not load up. After that the extension loaded but now it did not have UI elements (images & icons) as expected.

Can you please check out what went wrong and what I need to do to fix this?
Also do I need to upload another version with all the URLs specified? If so, can you please let me know asap?

**Comment by BarryCarlyon** [comment]
The GitHub Twitch 3rd party bug tracking, isn't a place for general support on extension development

For support you either want 
- Forums: https://discuss.dev.twitch.tv/
- Discord: https://link.twitch.tv/devchat

Since images are not loading this suggests the image source for your images is not in the CSP and you need to test that out

https://discuss.dev.twitch.tv/t/new-extensions-policy-for-content-security-policy-csp-directives-and-timeline-for-enforcement/33695/8

Covers the new CSP and the thread has some advice on testing.

If you refer to the console the console should be reporting what is violating the CSP and then you can determine how to solve this

**Comment by ronaksv** [comment]
Thanks for that. I think I will have to submit this new version and get it approved.

**Comment by jbulava** [comment]
Thanks for replying promptly, Barry. Closing this out since it's related to CSP enforcement rather than a bug.
