### ISSUE TITLE
Chance for a chat message to skip during high traffic loads

### ISSUE THREAD

**Issue by lejara** [twitchdev/issues#562]
**Brief description**

Based on my local testing,
By using two chats instances and the third party tool chatterino;
in different networks.

When a chat is under high load and there's a lag period(chat freezes for a second).
If a user sent a message all other end users will not see the message, but for the sender it looks like it was sent.

**How to reproduce**

- open two chat clients in a channel that are under high load
- send a message when it slightly freezes
- check other chat, the message might not be there

**Expected behavior**

When the user sends a message all other end users can see it in their timeline

**Screenshots**

(none)

**Additional context or questions**

Is this a known bug?

**Comment by gmt2001** [comment]
The Twitch website is known to show the message in the feed of the sender regardless of send success and not provide any feedback of the failure (other than the inevitable _Connected to chat_ message).

In the instance you are describing, the message actually failed to send due to the connection dropping, but the JavaScript in the sending clients browser adds it to the chat feed on that client's screen anyway

**Comment by TETYYS** [comment]
messages being dropped in high traffic chats is intended, last time I asked it on twitchdev stream or somewhere similar, they said its for performance purposes

**Comment by Xemdo** [comment]
Twitch's IRC server doesn't send an echo when a message is sent into chat, and it doesn't deliver any kind of failure notice is a message fails to send. Messages can be dropped for a lot of reasons, one of them being high load as you noted.
Therefore, this should be seen as expected behavior.
