### ISSUE TITLE
Add a Note about CSP can't be done via Meta Tags

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#565]
**Brief description**

Add a note to

https://dev.twitch.tv/docs/extensions#restrictions-on-content

And per haps the console

to include a "huge fluff off box" that says "no you cannot set CSP using meta tabs, please set CSP via the developer console"

Or words to that effect

**Additional context or questions**

A number of people have been in the Discord trying to use meta tags to set CSP

**Comment by scott-a-white** [comment]
Hi @BarryCarlyon. I'm going through the doc issues and updating the doc. Would you please help me understand this issue? Are you suggesting adding the note for this content under Restrictions On Content:

The Content Security Policy is dynamically constructed for each Extension and includes the allowlists provided in the developer console configuration. Below is a CSP example that could be expected for an Extension. Line spacing has been used instead of semicolons for readability.

> content-security-policy:
>   default-src 'self' https://<extension_id>.ext-twitch.tv

What are the "meta tabs" you're referring to?
Are you suggesting that people see the "content-security-policy:" example and think that they can edit a file with this information instead of using the developer console to configure this information? 
What file does the developer console create that contains this information that people might think they could edit manually?

Thanks for the help, much appreciated!

**Comment by BarryCarlyon** [comment]
Meta tags as in _HTML meta tags_

People have been trying to do

```html
<meta http-equiv="Content-Security-Policy" content="default-src 'self'">
```

Which is not correct for Twitch Extensions.

https://content-security-policy.com/examples/meta/

People are trying to use their HTML files to define policy instead of the developer console.

**Comment by scott-a-white** [comment]
Thanks for reporting the issue. Fixed: https://dev.twitch.tv/docs/extensions#restrictions-on-content.
