### ISSUE TITLE
.ics streaming schedule returns timestamp in wrong format

### ISSUE THREAD

**Issue by Cayllen** [twitchdev/issues#679]
The issue is that in the .ics file from Twitch the timezone in DTSTART/DTEND is declared with a leading "/"
```
DTSTART;TZID=/Europe/Stockholm:20221021T200000
DTEND;TZID=/Europe/Stockholm:20221021T210000
```

According to the discussion in this issue here: https://github.com/collective/icalendar/issues/466
the leading "/" is indicating that the timezone is supposed to be globally unique, thus the TZ is only defined in this calendar and it is not to be used anywhere else! This is clearly not the case that is meant here by Twitch: We are talking about a known timezone (Europe/Stockholm)
Thus there should be no leading "/"

This issue led to having wrong times when parsing the ics file

**Comment by jbulava** [comment]
Thanks for this post; the link to collective/icalendar was also very helpful. The engineering team behind this functionality has investigated the issue (ticket VXCHAN-2347 for internal reference). However, a proposed fix proved to be unsuccessful and the necessary changes identified to provide timezone data that fully meets the iCalendar spec is a level of complexity that cannot be prioritized at this time.  Instead of leaving this issue open without a reply, the team recommended closing the report as a "won't fix" for now.
