### ISSUE TITLE
Google Analytics in Extensions - July 2023 deadline

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#689]
**Brief description**

June 2023 will see the end of Google Analytics supporting Universal Analytics
Requiring users to move to Google Analytics 4

This is on a different domain to current. So the CSP requires modification.

Initially this seems to require allowing `script` and `connect` rules to include
 - `https://www.googletagmanager.com/`
 - `https://*.google-analytics.com/`

**Additional context or questions**

Filing as a bug (github) rather than a feature request (uservoice) as if CSP not fixed in time, there will be a flood of Extensions into the  queue for the revision and/or removal of GA for something else if Twitch doesn't support new Google Analytics

https://support.google.com/analytics/answer/11583528?hl=en

**Comment by jbulava** [comment]
While there isn't an exact date to provide for the Extensions CSP to be updated, the team is looking to prioritize this addition for early 2023 to give developers plenty of time for review submissions before Google's deadline.

**Comment by luisvinicius09** [comment]
Hey, do you guys have new updates on this?

**Comment by jbulava** [comment]
@luisvinicius09 This is now actively being worked on, so we should have an update soon for this ticket.

**Comment by marcandrews** [comment]
Any updates on this? The CSP has been updated and everything is working as expected in my hosted test, but my extension  review is currently stuck in a pending state. Any ideas?

Extension client ID: tdldrg6rlw5eewiwcpxo3dv0obyckc
Version 0.14.1 (ref:_00D5A16sES._5006e1veUIu:ref)

**Comment by BarryCarlyon** [comment]
Extension review issues are between you and extension review, if it's pending you should of got an email from extension review with issues. Or you are stuck due to the layoffs. Either way the bug tracker can't help you here, you need to contact the extension review team

**Comment by schneckentempo** [comment]
any updates on this? the deadline is just 3 days away

**Comment by BarryCarlyon** [comment]
Yes.

The CSP was updated.
The CSP guide was updated
The main "using analytics in extensions guide" was not

my notes follow:


In your view HTML(s), before closing head tag

```html
</head>
```

add, generally immediately after your Extension Helper JS Script include

```html
<script async src="https://www.googletagmanager.com/gtag/js?id=GCODE"></script>
```

- Substitute in your GCODE [note 1]

Then in an external javascript file

```js
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());

gtag('config', 'GCODE');
```

- Substitute in your GCODE [note 1]

for additional GDPR-ness

```js
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());

gtag('config', 'GCODE', { 'anonymize_ip': true });
```

- Substitute in your GCODE [note 1]




[note 1] GCODE being the `Measurement ID` from

- Analytics dashboard
- Admin for the Property
- Data Streams

**Comment by schneckentempo** [comment]
@BarryCarlyon @jbulava 
I tested our extension locally where everything worked fine. In hosted test log messages are printed in the console when used with the Google Analytics Debugging chrome-extension but the events do not reach the debug view on analytics site itself. I also added the rules of the original to the configuration where it is marked in the screen here https://github.com/twitchdev/issues/issues/755

There are minor differences to your notes like I do not use an external js file but directly declare another script tag after the first one. Also I use https://github.com/PriceRunner/react-ga4 due to migration. But as I said, locally everything works as expected.

> The CSP was updated.
> The CSP guide was updated
> The main "using analytics in extensions guide" was not

Could you please state clear if things should work in hosted test and if the mentioned changes are live already?

**Comment by schneckentempo** [comment]
Thank you very much for your explanations. There was one tiny detail missing:
After trying many different approaches to get it working in hosted test the solution was to initialize gtag with `cookie_flags` set. This already was a problem previously. I acutally did a test with setting `cookieFlags` (camelCase) like in the old docs but when looking closer it turned out with ga4 it has to be snake_case.

```
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());

gtag('config', 'GCODE', { cookie_flags: 'max-age=7200;secure;samesite=none');
```

**Comment by BarryCarlyon** [comment]
Good spot I'll add cookie_flags to my notes and next extension release(s)!
