### ISSUE TITLE
Twitch IRC tag "flags" is undocumented

### ISSUE THREAD

**Issue by Redmite** [twitchdev/issues#804]
In the twitch IRC tags documentation, there are multiple instances and examples of the "flags" tag being returned. But it is not documented, its use is related to automod but to what extent is not known.

https://dev.twitch.tv/docs/irc/tags/

If you send any message with words that are detected by automod the "flags" tag will be populated. Otherwise it will be left blank or be populated with a space.

Example of a message with "flags" populated:
https://paste.ivr.fi/raw/rotyqadupy

Ticket here:
https://twitch.uservoice.com/forums/310213-developers/suggestions/46906180-twitch-irc-tag-flags-is-undocumented

**Comment by thedist** [comment]
Some IRC tags are undocumented by design as they are not always intended for 3rd party consumption and are to power 1st party functionality.

Additionally Twitch often change undocumented tags, use them in different ways, and use tags for experiments, so the lack of documentation is not a bug nor something that really needs a feature request.

**Comment by Xemdo** [comment]
All public tags have been updated:
https://dev.twitch.tv/docs/chat/irc/

**Comment by rayer456** [comment]
Still don't see the tag flags mentioned anywhere except in examples. This came to my attention when my message parser started failing when I used cursed words in my messages. A normal flags value was empty before `flags=`. But now it looked something like this `flags=5-7:P.3` where the 5-7 are the character indexes of the bad word. No clue what P.3 means here. Anyway my parser started failing because of the extra colon in the message string.
