### ISSUE TITLE
genshin and twitch link bug

### ISSUE THREAD

**Issue by akane053** [twitchdev/issues#872]
**Brief description**
i cant link my twitch acc to genshin to get the rewards. 
It give me a "status":401,"message":"invalid csrf token" error 
**How to reproduce**

**Expected behavior**

**Screenshots**

**Additional context or questions**

**Comment by Emilgardis** [comment]
This sounds like genshin is telling you to navigate to authenticate, they give you a csrf in the `state` parameter, and then when you've authenticated and are redirected to genshins servers they don't recognize the csrf in the `state` parameter. Is the error message on id.twitch.tv or one of genshins website?

The issue is most likely on their side and you should reach out to them.

**Comment by iProdigy** [comment]
Duplicate of #29 - try using chrome instead of firefox when linking your accounts

**Comment by Xemdo** [comment]
Closing as duplicate of #29
