### ISSUE TITLE
TWITCH BUG

### ISSUE THREAD

**Issue by chat06** [twitchdev/issues#96]
**Brief description**

sorry not ENGLISH first langage.....
Recomandation inversed than normal if you dont even click on SHOW more you only see the 2 BUG reccomande on top very strange....
**How to reproduce**
work every time very easy
**Expected behavior**
check by yourelf got ot go BOTTOM  list instead top list like if REVERSE reccomandation !
_____________________________________________________________________________________
**Screenshots**
https://imgbb.com/ =====> https://ibb.co/FbQqkKY
https://www.zupimages.net/up.php =====> https://zupimages.net/viewer.php?id=20/17/nv2g.jpg
https://hostpic.xyz/=====> https://hostpic.fr/uploads/20200426/13c6de53a44411ca0aaac27b779138581eaf1f6b.jpg
_________________________________________________________________________________
**Additional context or questions**
really sure if not done on purpose by Twtch engine.
how can GRUBB w3  7time World champion is not on recc list and guy with +10k online viewer is last... something is UP...

**Comment by chat06** [comment]
TWITCH

**Comment by BarryCarlyon** [comment]
This issue is not relevant to this GitHub.

The recommendation engine is a black box and works how it works. Channel Recommendations are not necessarily sorted how you think they should be, or include the people you think it should.

There is nothing anyone on this repo can do, and it's not an authentication issue.

Also you screenshots are all the same and contain slander against the streamers in question.

**Comment by jbulava** [comment]
This does not apply to developer products. Please feel free to submit feature requests or bug reports for Twitch.tv at twitch.uservoice.com.
